#!/usr/bin/env bash
#A Bash script that pingss an IP address passed as an argument
#Requirements:
#Accepts a string as an argument
#Display Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
#if no argument is passed Ping the IP 5 times

if [ $# -eq 0 ]; then
   echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
   exit
elif [ $# -gt 1 ]; then 
   echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
   exit
else
   ping "$1" -c 5
fi
