#!/usr/bin/env bash
#Using what you did for task #1, make your fix short and sweet

sudo sed -Ei 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sudo sed -Ei 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -Ei 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
pkill apache2
chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf | sudo -u nginx service nginx restart

